name: disk_kit_macos_example
description: "Demonstrates how to use the disk_kit_macos plugin."
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  disk_kit: ^1.0.0

dev_dependencies:
  disk_kit_platform_interface: ^1.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# Use the macOS plugin shipped alongside this example.
dependency_overrides:
  disk_kit_macos:
    path: ../

flutter:

  uses-material-design: true
